### ISSUE TITLE
Store bitstreams with Git LFS

### ISSUE THREAD

**Issue by frankplow** [ffvvc/tests#13]
Some of the bitstreams in the test repo are gibibytes large. Moving them around can therefore take quite a long time. Particularly as we seldom (if never) make changes to the contents of the bitstreams themselves, a better solution may be Git LFS:
* https://git-lfs.com/
* https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage

This would make it quicker to clone and update this repo. This principal disadvantage is that the user would have to have the Git LFS extension installed to clone the repo.

I would be happy to implement this, but @nuomi2021 I thought I would get your opinion before getting started on it.

**Comment by nuomi2021** [comment]
@frankplow , sure please go ahead. 
thank you

**Comment by frankplow** [comment]
Not needed now there is the ability to download files from URLs, as implemented in #26.
